name: (Dev) Upload To Azure Blob Storage
on:
  push:
    branches:
      - develop

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build shaded Jar
        run: gradle shadowJar
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.TOKEN }}

      - name: Upload Jar
        uses: azure/CLI@v1
        env:
          CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
          CONTAINER_NAME: ${{ secrets.DEV_CONTAINER }}
        with:
          inlineScript: az storage blob upload-batch --connection-string $CONNECTION_STRING --source Impl/build/libs --destination $CONTAINER_NAME --destination-path hyrame --overwrite